[package]
name = "rs-lox"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["cargo"] }
phf = { version = "0.11", features = ["macros"] }
thiserror = "1.0.63"
